exchangerate:
    path: /api/exchange-rates
    controller: App\Infrastructure\Controller\ExchangeRateController

setupcheck:
    path: /api/setup-check
    controller: App\Infrastructure\Controller\DefaultController::setupCheck

index:
    path: /{wildcard}
    defaults: {
        _controller: App\Infrastructure\Controller\DefaultController::index
    }
    requirements:
        wildcard: .*

